spring.application.name=tu-vcs
spring.datasource.url=jdbc:postgresql://localhost:5432/vcs_db
spring.datasource.username=vcs_user
spring.datasource.password=vcs_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081/realms/vcs-realm

spring.profiles.active=test
